"use client"

import { useEffect, useState } from "react";

// Typy

type Word = {
  id: number;
  pl: string;
  en: string;
};

type SlotWord = {
  id: number | null;
  word: string | null;
};

type Difficulty = "easy" | "medium" | "hard";

// Dane

const easyWords: Word[] = [
  { id: 1, pl: "pies", en: "dog" },
  { id: 2, pl: "kot", en: "cat" },
  { id: 3, pl: "dom", en: "house" },
  { id: 4, pl: "woda", en: "water" },
  { id: 5, pl: "chleb", en: "bread" },
  { id: 6, pl: "oko", en: "eye" },
  { id: 7, pl: "ucho", en: "ear" },
  { id: 8, pl: "noga", en: "leg" },
  { id: 9, pl: "dziecko", en: "child" },
  { id: 10, pl: "matka", en: "mother" },
  { id: 11, pl: "ojciec", en: "father" },
  { id: 12, pl: "kawa", en: "coffee" },
  { id: 13, pl: "herbata", en: "tea" },
  { id: 14, pl: "szkoła", en: "school" },
  { id: 15, pl: "nauczyciel", en: "teacher" },
  { id: 16, pl: "uczeń", en: "student" },
  { id: 17, pl: "książka", en: "book" },
  { id: 18, pl: "łóżko", en: "bed" },
  { id: 19, pl: "okno", en: "window" },
  { id: 20, pl: "drzwi", en: "door" },
  { id: 21, pl: "samochód", en: "car" },
  { id: 22, pl: "rower", en: "bicycle" },
  { id: 23, pl: "jabłko", en: "apple" },
  { id: 24, pl: "banan", en: "banana" },
  { id: 25, pl: "noc", en: "night" },
  { id: 26, pl: "dzień", en: "day" },
  { id: 27, pl: "słońce", en: "sun" },
  { id: 28, pl: "księżyc", en: "moon" },
  { id: 29, pl: "gwiazda", en: "star" },
  { id: 30, pl: "drzewo", en: "tree" },
  { id: 31, pl: "las", en: "forest" },
  { id: 32, pl: "trawa", en: "grass" },
  { id: 33, pl: "kwiat", en: "flower" },
  { id: 34, pl: "miasto", en: "city" },
  { id: 35, pl: "wieś", en: "village" },
  { id: 36, pl: "ulica", en: "street" },
  { id: 37, pl: "chodnik", en: "sidewalk" },
  { id: 38, pl: "sklep", en: "shop" },
  { id: 39, pl: "pieniądze", en: "money" },
  { id: 40, pl: "telefon", en: "phone" },
  { id: 41, pl: "komputer", en: "computer" },
  { id: 42, pl: "ręka", en: "hand" },
  { id: 43, pl: "stopa", en: "foot" },
  { id: 44, pl: "palec", en: "finger" },
  { id: 45, pl: "włos", en: "hair" },
  { id: 46, pl: "nos", en: "nose" },
  { id: 47, pl: "usta", en: "mouth" },
  { id: 48, pl: "język", en: "tongue" },
  { id: 49, pl: "serce", en: "heart" },
  { id: 50, pl: "głowa", en: "head" },
  { id: 51, pl: "piesek", en: "puppy" },
  { id: 52, pl: "kotka", en: "kitten" },
  { id: 53, pl: "ryba", en: "fish" },
  { id: 54, pl: "ptak", en: "bird" },
  { id: 55, pl: "krzesło", en: "chair" },
  { id: 56, pl: "stół", en: "table" },
  { id: 57, pl: "słoik", en: "jar" },
  { id: 58, pl: "jabłko", en: "apple" },
  { id: 59, pl: "pomarańcza", en: "orange" },
  { id: 60, pl: "winogrona", en: "grapes" },
  { id: 61, pl: "mleko", en: "milk" },
  { id: 62, pl: "jajko", en: "egg" },
  { id: 63, pl: "ser", en: "cheese" },
  { id: 64, pl: "mięso", en: "meat" },
  { id: 65, pl: "ryż", en: "rice" },
  { id: 66, pl: "cukier", en: "sugar" },
  { id: 67, pl: "sól", en: "salt" },
  { id: 68, pl: "pieprz", en: "pepper" },
  { id: 69, pl: "zupa", en: "soup" },
  { id: 70, pl: "masło", en: "butter" },
  { id: 71, pl: "but", en: "shoe" },
  { id: 72, pl: "czapka", en: "hat" },
  { id: 73, pl: "koszula", en: "shirt" },
  { id: 74, pl: "spodnie", en: "pants" },
  { id: 75, pl: "sukienka", en: "dress" },
  { id: 76, pl: "kurtka", en: "jacket" },
  { id: 77, pl: "deszcz", en: "rain" },
  { id: 78, pl: "śnieg", en: "snow" },
  { id: 79, pl: "wiatr", en: "wind" },
  { id: 80, pl: "chmura", en: "cloud" },
  { id: 81, pl: "ogień", en: "fire" },
  { id: 82, pl: "ziemia", en: "earth" },
  { id: 83, pl: "kamień", en: "stone" },
  { id: 84, pl: "piasek", en: "sand" },
  { id: 85, pl: "morze", en: "sea" },
  { id: 86, pl: "rzeka", en: "river" },
  { id: 87, pl: "jezioro", en: "lake" },
  { id: 88, pl: "góra", en: "mountain" },
  { id: 89, pl: "droga", en: "road" },
  { id: 90, pl: "most", en: "bridge" },
  { id: 91, pl: "pociąg", en: "train" },
  { id: 92, pl: "samolot", en: "plane" },
  { id: 93, pl: "statek", en: "ship" },
  { id: 94, pl: "rower", en: "bike" },
  { id: 95, pl: "kwiat", en: "flower" },
  { id: 96, pl: "liść", en: "leaf" },
  { id: 97, pl: "motyl", en: "butterfly" },
  { id: 98, pl: "pszczoła", en: "bee" },
  { id: 99, pl: "mrówka", en: "ant" },
  { id: 100, pl: "pies", en: "dog" },
  { id: 101, pl: "kot", en: "cat" },
  { id: 102, pl: "pies", en: "dog" },
  { id: 103, pl: "ryba", en: "fish" },
  { id: 104, pl: "ptak", en: "bird" },
  { id: 105, pl: "słoń", en: "elephant" },
  { id: 106, pl: "lew", en: "lion" },
  { id: 107, pl: "tygrys", en: "tiger" },
  { id: 108, pl: "krowa", en: "cow" },
  { id: 109, pl: "koń", en: "horse" },
  { id: 110, pl: "owca", en: "sheep" },
  { id: 111, pl: "kura", en: "hen" },
  { id: 112, pl: "jajo", en: "egg" },
  { id: 113, pl: "ser", en: "cheese" },
  { id: 114, pl: "masło", en: "butter" },
  { id: 115, pl: "chleb", en: "bread" },
  { id: 116, pl: "ryż", en: "rice" },
  { id: 117, pl: "ziemniak", en: "potato" },
  { id: 118, pl: "marchewka", en: "carrot" },
  { id: 119, pl: "cebula", en: "onion" },
  { id: 120, pl: "czosnek", en: "garlic" },
  { id: 121, pl: "pomidor", en: "tomato" },
  { id: 122, pl: "sałata", en: "lettuce" },
  { id: 123, pl: "jabłko", en: "apple" },
  { id: 124, pl: "banan", en: "banana" },
  { id: 125, pl: "pomarańcza", en: "orange" },
  { id: 126, pl: "winogrona", en: "grapes" },
  { id: 127, pl: "cytryna", en: "lemon" },
  { id: 128, pl: "truskawka", en: "strawberry" },
  { id: 129, pl: "wiśnia", en: "cherry" },
  { id: 130, pl: "woda", en: "water" },
  { id: 131, pl: "mleko", en: "milk" },
  { id: 132, pl: "sok", en: "juice" },
  { id: 133, pl: "kawa", en: "coffee" },
  { id: 134, pl: "herbata", en: "tea" },
  { id: 135, pl: "cukier", en: "sugar" },
  { id: 136, pl: "sól", en: "salt" },
  { id: 137, pl: "pieprz", en: "pepper" },
  { id: 138, pl: "ciasto", en: "cake" },
  { id: 139, pl: "lód", en: "ice cream" },
  { id: 140, pl: "czekolada", en: "chocolate" },
  { id: 141, pl: "mięso", en: "meat" },
  { id: 142, pl: "kurczak", en: "chicken" },
  { id: 143, pl: "ryba", en: "fish" },
  { id: 144, pl: "owoce", en: "fruit" },
  { id: 145, pl: "warzywa", en: "vegetables" },
  { id: 146, pl: "dom", en: "house" },
  { id: 147, pl: "pokój", en: "room" },
  { id: 148, pl: "kuchnia", en: "kitchen" },
  { id: 149, pl: "łazienka", en: "bathroom" },
  { id: 150, pl: "sypialnia", en: "bedroom" },
  { id: 151, pl: "okno", en: "window" },
  { id: 152, pl: "drzwi", en: "door" },
  { id: 153, pl: "stół", en: "table" },
  { id: 154, pl: "krzesło", en: "chair" },
  { id: 155, pl: "łóżko", en: "bed" },
  { id: 156, pl: "szafa", en: "wardrobe" },
  { id: 157, pl: "lampa", en: "lamp" },
  { id: 158, pl: "komputer", en: "computer" },
  { id: 159, pl: "telefon", en: "phone" },
  { id: 160, pl: "telewizor", en: "TV" },
  { id: 161, pl: "książka", en: "book" },
  { id: 162, pl: "zeszyt", en: "notebook" },
  { id: 163, pl: "długopis", en: "pen" },
  { id: 164, pl: "ołówek", en: "pencil" },
  { id: 165, pl: "papier", en: "paper" },
  { id: 166, pl: "buty", en: "shoes" },
  { id: 167, pl: "koszula", en: "shirt" },
  { id: 168, pl: "spodnie", en: "pants" },
  { id: 169, pl: "sukienka", en: "dress" },
  { id: 170, pl: "kurtka", en: "jacket" },
  { id: 171, pl: "czapka", en: "hat" },
  { id: 172, pl: "rękawiczki", en: "gloves" },
  { id: 173, pl: "szalik", en: "scarf" },
  { id: 174, pl: "noc", en: "night" },
  { id: 175, pl: "dzień", en: "day" },
  { id: 176, pl: "rano", en: "morning" },
  { id: 177, pl: "wieczór", en: "evening" },
  { id: 178, pl: "weekend", en: "weekend" },
  { id: 179, pl: "poniedziałek", en: "Monday" },
  { id: 180, pl: "wtorek", en: "Tuesday" },
  { id: 181, pl: "środa", en: "Wednesday" },
  { id: 182, pl: "czwartek", en: "Thursday" },
  { id: 183, pl: "piątek", en: "Friday" },
  { id: 184, pl: "sobota", en: "Saturday" },
  { id: 185, pl: "niedziela", en: "Sunday" },
  { id: 186, pl: "woda", en: "water" },
  { id: 187, pl: "ogień", en: "fire" },
  { id: 188, pl: "ziemia", en: "earth" },
  { id: 189, pl: "powietrze", en: "air" },
  { id: 190, pl: "niebo", en: "sky" },
  { id: 191, pl: "morze", en: "sea" },
  { id: 192, pl: "rzeka", en: "river" },
  { id: 193, pl: "jezioro", en: "lake" },
  { id: 194, pl: "las", en: "forest" },
  { id: 195, pl: "drzewo", en: "tree" },
  { id: 196, pl: "kwiat", en: "flower" },
  { id: 197, pl: "trawa", en: "grass" },
  { id: 198, pl: "kamień", en: "stone" },
  { id: 199, pl: "piasek", en: "sand" },
  { id: 200, pl: "góra", en: "mountain" },
  { id: 201, pl: "droga", en: "road" },
  { id: 202, pl: "most", en: "bridge" },
  { id: 203, pl: "pociąg", en: "train" },
  { id: 204, pl: "samolot", en: "plane" },
  { id: 205, pl: "rower", en: "bicycle" },
  { id: 206, pl: "statek", en: "ship" },
  { id: 207, pl: "autobus", en: "bus" },
  { id: 208, pl: "tak", en: "yes" },
  { id: 209, pl: "nie", en: "no" },
  { id: 210, pl: "proszę", en: "please" },
  { id: 211, pl: "dziękuję", en: "thank you" },
  { id: 212, pl: "przepraszam", en: "sorry" },
  { id: 213, pl: "cześć", en: "hello" },
  { id: 214, pl: "do widzenia", en: "goodbye" },
  { id: 215, pl: "dobry", en: "good" },
  { id: 216, pl: "zły", en: "bad" },
  { id: 217, pl: "duży", en: "big" },
  { id: 218, pl: "mały", en: "small" },
  { id: 219, pl: "długi", en: "long" },
  { id: 220, pl: "krótki", en: "short" },
  { id: 221, pl: "szybki", en: "fast" },
  { id: 222, pl: "wolny", en: "slow" },
  { id: 223, pl: "gorący", en: "hot" },
  { id: 224, pl: "zimny", en: "cold" },
  { id: 225, pl: "nowy", en: "new" },
  { id: 226, pl: "stary", en: "old" },
  { id: 227, pl: "łatwy", en: "easy" },
  { id: 228, pl: "trudny", en: "hard" },
  { id: 229, pl: "piękny", en: "beautiful" },
  { id: 230, pl: "brzydki", en: "ugly" },
  { id: 231, pl: "mocny", en: "strong" },
  { id: 232, pl: "słaby", en: "weak" },
  { id: 233, pl: "bogaty", en: "rich" },
  { id: 234, pl: "biedny", en: "poor" },
  { id: 235, pl: "głośny", en: "loud" },
  { id: 236, pl: "cichy", en: "quiet" },
  { id: 237, pl: "wysoki", en: "tall" },
  { id: 238, pl: "niski", en: "short" },
  { id: 239, pl: "gruby", en: "fat" },
  { id: 240, pl: "chudy", en: "thin" },
  { id: 241, pl: "czysty", en: "clean" },
  { id: 242, pl: "brudny", en: "dirty" },
  { id: 243, pl: "mokry", en: "wet" },
  { id: 244, pl: "suchy", en: "dry" },
  { id: 245, pl: "słodki", en: "sweet" },
  { id: 246, pl: "gorzki", en: "bitter" },
  { id: 247, pl: "kwaśny", en: "sour" },
  { id: 248, pl: "słony", en: "salty" },
  { id: 249, pl: "dobry", en: "nice" },
  { id: 250, pl: "zły", en: "evil" },
  { id: 251, pl: "jasny", en: "bright" },
  { id: 252, pl: "ciemny", en: "dark" },
  { id: 253, pl: "pełny", en: "full" },
  { id: 254, pl: "pusty", en: "empty" },
  { id: 255, pl: "gruby", en: "thick" },
  { id: 256, pl: "cienki", en: "thin" },
  { id: 257, pl: "miękki", en: "soft" },
  { id: 258, pl: "twardy", en: "hard" },
  { id: 259, pl: "ładny", en: "pretty" },
  { id: 260, pl: "brzydki", en: "ugly" },
  { id: 261, pl: "ciepły", en: "warm" },
  { id: 262, pl: "zimny", en: "cold" },
  { id: 263, pl: "wolny", en: "free" },
  { id: 264, pl: "zajęty", en: "busy" },
  { id: 265, pl: "mądry", en: "smart" },
  { id: 266, pl: "głupi", en: "stupid" },
  { id: 267, pl: "świeży", en: "fresh" },
  { id: 268, pl: "stary", en: "old" },
  { id: 269, pl: "szybki", en: "quick" },
  { id: 270, pl: "wolny", en: "slow" },
  { id: 271, pl: "silny", en: "powerful" },
  { id: 272, pl: "słaby", en: "weak" },
  { id: 273, pl: "łatwy", en: "simple" },
  { id: 274, pl: "trudny", en: "difficult" },
  { id: 275, pl: "wesoły", en: "happy" },
  { id: 276, pl: "smutny", en: "sad" },
  { id: 277, pl: "bogaty", en: "wealthy" },
  { id: 278, pl: "biedny", en: "poor" },
  { id: 279, pl: "piękny", en: "gorgeous" },
  { id: 280, pl: "brzydki", en: "hideous" },
  { id: 281, pl: "głośny", en: "noisy" },
  { id: 282, pl: "cichy", en: "silent" },
  { id: 283, pl: "jasny", en: "clear" },
  { id: 284, pl: "ciemny", en: "dim" },
  { id: 285, pl: "pełny", en: "complete" },
  { id: 286, pl: "pusty", en: "vacant" },
  { id: 287, pl: "gruby", en: "bulky" },
  { id: 288, pl: "cienki", en: "slim" },
  { id: 289, pl: "miękki", en: "pliable" },
  { id: 290, pl: "twardy", en: "rigid" },
  { id: 291, pl: "ładny", en: "lovely" },
  { id: 292, pl: "brzydki", en: "unsightly" },
  { id: 293, pl: "ciepły", en: "cozy" },
  { id: 294, pl: "zimny", en: "chilly" },
  { id: 295, pl: "wolny", en: "loose" },
  { id: 296, pl: "zajęty", en: "occupied" },
  { id: 297, pl: "mądry", en: "intelligent" },
  { id: 298, pl: "głupi", en: "foolish" },
  { id: 299, pl: "świeży", en: "crisp" },
  { id: 300, pl: "stary", en: "ancient" },
  { id: 301, pl: "dzień", en: "day" },
  { id: 302, pl: "noc", en: "night" },
  { id: 303, pl: "tydzień", en: "week" },
  { id: 304, pl: "miesiąc", en: "month" },
  { id: 305, pl: "rok", en: "year" },
  { id: 306, pl: "godzina", en: "hour" },
  { id: 307, pl: "minuta", en: "minute" },
  { id: 308, pl: "sekunda", en: "second" },
  { id: 309, pl: "rano", en: "morning" },
  { id: 310, pl: "wieczór", en: "evening" },
  { id: 311, pl: "dzisiaj", en: "today" },
  { id: 312, pl: "jutro", en: "tomorrow" },
  { id: 313, pl: "wczoraj", en: "yesterday" },
  { id: 314, pl: "człowiek", en: "person" },
  { id: 315, pl: "kobieta", en: "woman" },
  { id: 316, pl: "mężczyzna", en: "man" },
  { id: 317, pl: "dziecko", en: "child" },
  { id: 318, pl: "przyjaciel", en: "friend" },
  { id: 319, pl: "rodzina", en: "family" },
  { id: 320, pl: "szkoła", en: "school" },
  { id: 321, pl: "nauczyciel", en: "teacher" },
  { id: 322, pl: "uczeń", en: "student" },
  { id: 323, pl: "książka", en: "book" },
  { id: 324, pl: "zeszyt", en: "notebook" },
  { id: 325, pl: "długopis", en: "pen" },
  { id: 326, pl: "ołówek", en: "pencil" },
  { id: 327, pl: "biurko", en: "desk" },
  { id: 328, pl: "krzesło", en: "chair" },
  { id: 329, pl: "komputer", en: "computer" },
  { id: 330, pl: "telefon", en: "phone" },
  { id: 331, pl: "samochód", en: "car" },
  { id: 332, pl: "rower", en: "bicycle" },
  { id: 333, pl: "autobus", en: "bus" },
  { id: 334, pl: "pociąg", en: "train" },
  { id: 335, pl: "samolot", en: "plane" },
  { id: 336, pl: "dom", en: "house" },
  { id: 337, pl: "pokój", en: "room" },
  { id: 338, pl: "kuchnia", en: "kitchen" },
  { id: 339, pl: "łazienka", en: "bathroom" },
  { id: 340, pl: "sypialnia", en: "bedroom" },
  { id: 341, pl: "drzwi", en: "door" },
  { id: 342, pl: "okno", en: "window" },
  { id: 343, pl: "stół", en: "table" },
  { id: 344, pl: "lampa", en: "lamp" },
  { id: 345, pl: "łóżko", en: "bed" },
  { id: 346, pl: "szafa", en: "wardrobe" },
  { id: 347, pl: "buty", en: "shoes" },
  { id: 348, pl: "koszula", en: "shirt" },
  { id: 349, pl: "spodnie", en: "pants" },
  { id: 350, pl: "sukienka", en: "dress" },
  { id: 351, pl: "kurtka", en: "jacket" },
  { id: 352, pl: "czapka", en: "hat" },
  { id: 353, pl: "rękawiczki", en: "gloves" },
  { id: 354, pl: "szalik", en: "scarf" },
  { id: 355, pl: "pogoda", en: "weather" },
  { id: 356, pl: "słońce", en: "sun" },
  { id: 357, pl: "deszcz", en: "rain" },
  { id: 358, pl: "śnieg", en: "snow" },
  { id: 359, pl: "wiatr", en: "wind" },
  { id: 360, pl: "chmura", en: "cloud" },
  { id: 361, pl: "burza", en: "storm" },
  { id: 362, pl: "tęcza", en: "rainbow" },
  { id: 363, pl: "morze", en: "sea" },
  { id: 364, pl: "jezioro", en: "lake" },
  { id: 365, pl: "rzeka", en: "river" },
  { id: 366, pl: "las", en: "forest" },
  { id: 367, pl: "góra", en: "mountain" },
  { id: 368, pl: "drzewo", en: "tree" },
  { id: 369, pl: "kwiat", en: "flower" },
  { id: 370, pl: "trawa", en: "grass" },
  { id: 371, pl: "kamień", en: "stone" },
  { id: 372, pl: "piasek", en: "sand" },
  { id: 373, pl: "droga", en: "road" },
  { id: 374, pl: "most", en: "bridge" },
  { id: 375, pl: "miasto", en: "city" },
  { id: 376, pl: "wieś", en: "village" },
  { id: 377, pl: "ulica", en: "street" },
  { id: 378, pl: "sklep", en: "shop" },
  { id: 379, pl: "restauracja", en: "restaurant" },
  { id: 380, pl: "hotel", en: "hotel" },
  { id: 381, pl: "szpital", en: "hospital" },
  { id: 382, pl: "apteka", en: "pharmacy" },
  { id: 383, pl: "policja", en: "police" },
  { id: 384, pl: "straż", en: "fire brigade" },
  { id: 385, pl: "bank", en: "bank" },
  { id: 386, pl: "kino", en: "cinema" },
  { id: 387, pl: "teatr", en: "theatre" },
  { id: 388, pl: "muzeum", en: "museum" },
  { id: 389, pl: "biblioteka", en: "library" },
  { id: 390, pl: "park", en: "park" },
  { id: 391, pl: "plac", en: "square" },
  { id: 392, pl: "most", en: "bridge" },
  { id: 393, pl: "ratusz", en: "town hall" },
  { id: 394, pl: "kościół", en: "church" },
  { id: 395, pl: "zoo", en: "zoo" },
  { id: 396, pl: "stadion", en: "stadium" },
  { id: 397, pl: "lotnisko", en: "airport" },
  { id: 398, pl: "dworzec", en: "station" },
  { id: 399, pl: "kino", en: "cinema" },
  { id: 400, pl: "restauracja", en: "restaurant" },
  { id: 401, pl: "pies", en: "dog" },
  { id: 402, pl: "kot", en: "cat" },
  { id: 403, pl: "koń", en: "horse" },
  { id: 404, pl: "krowa", en: "cow" },
  { id: 405, pl: "owca", en: "sheep" },
  { id: 406, pl: "świnia", en: "pig" },
  { id: 407, pl: "kurczak", en: "chicken" },
  { id: 408, pl: "ryba", en: "fish" },
  { id: 409, pl: "ptak", en: "bird" },
  { id: 410, pl: "żaba", en: "frog" },
  { id: 411, pl: "motyl", en: "butterfly" },
  { id: 412, pl: "mrówka", en: "ant" },
  { id: 413, pl: "pająk", en: "spider" },
  { id: 414, pl: "wąż", en: "snake" },
  { id: 415, pl: "lew", en: "lion" },
  { id: 416, pl: "tygrys", en: "tiger" },
  { id: 417, pl: "słoń", en: "elephant" },
  { id: 418, pl: "małpa", en: "monkey" },
  { id: 419, pl: "niedźwiedź", en: "bear" },
  { id: 420, pl: "wil", en: "wolf" },
  { id: 421, pl: "lis", en: "fox" },
  { id: 422, pl: "zając", en: "hare" },
  { id: 423, pl: "królik", en: "rabbit" },
  { id: 424, pl: "kaczka", en: "duck" },
  { id: 425, pl: "gęś", en: "goose" },
  { id: 426, pl: "łabędź", en: "swan" },
  { id: 427, pl: "ryś", en: "lynx" },
  { id: 428, pl: "wiewiórka", en: "squirrel" },
  { id: 429, pl: "jezioro", en: "lake" },
  { id: 430, pl: "rzeka", en: "river" },
  { id: 431, pl: "morze", en: "sea" },
  { id: 432, pl: "ocean", en: "ocean" },
  { id: 433, pl: "góra", en: "mountain" },
  { id: 434, pl: "wulkan", en: "volcano" },
  { id: 435, pl: "lód", en: "ice" },
  { id: 436, pl: "śnieg", en: "snow" },
  { id: 437, pl: "deszcz", en: "rain" },
  { id: 438, pl: "wiatr", en: "wind" },
  { id: 439, pl: "słońce", en: "sun" },
  { id: 440, pl: "księżyc", en: "moon" },
  { id: 441, pl: "gwiazda", en: "star" },
  { id: 442, pl: "niebo", en: "sky" },
  { id: 443, pl: "chmura", en: "cloud" },
  { id: 444, pl: "tęcza", en: "rainbow" },
  { id: 445, pl: "las", en: "forest" },
  { id: 446, pl: "drzewo", en: "tree" },
  { id: 447, pl: "krzew", en: "bush" },
  { id: 448, pl: "kwiat", en: "flower" },
  { id: 449, pl: "trawa", en: "grass" },
  { id: 450, pl: "piasek", en: "sand" },
  { id: 451, pl: "kamień", en: "stone" },
  { id: 452, pl: "ziemia", en: "earth" },
  { id: 453, pl: "ogień", en: "fire" },
  { id: 454, pl: "woda", en: "water" },
  { id: 455, pl: "powietrze", en: "air" },
  { id: 456, pl: "dom", en: "house" },
  { id: 457, pl: "mieszkanie", en: "apartment" },
  { id: 458, pl: "pokój", en: "room" },
  { id: 459, pl: "kuchnia", en: "kitchen" },
  { id: 460, pl: "łazienka", en: "bathroom" },
  { id: 461, pl: "sypialnia", en: "bedroom" },
  { id: 462, pl: "drzwi", en: "door" },
  { id: 463, pl: "okno", en: "window" },
  { id: 464, pl: "stół", en: "table" },
  { id: 465, pl: "krzesło", en: "chair" },
  { id: 466, pl: "łóżko", en: "bed" },
  { id: 467, pl: "szafa", en: "wardrobe" },
  { id: 468, pl: "lampa", en: "lamp" },
  { id: 469, pl: "telefon", en: "phone" },
  { id: 470, pl: "komputer", en: "computer" },
  { id: 471, pl: "telewizor", en: "television" },
  { id: 472, pl: "radio", en: "radio" },
  { id: 473, pl: "zegarek", en: "watch" },
  { id: 474, pl: "samochód", en: "car" },
  { id: 475, pl: "rower", en: "bicycle" },
  { id: 476, pl: "autobus", en: "bus" },
  { id: 477, pl: "pociąg", en: "train" },
  { id: 478, pl: "samolot", en: "plane" },
  { id: 479, pl: "statek", en: "ship" },
  { id: 480, pl: "droga", en: "road" },
  { id: 481, pl: "ulica", en: "street" },
  { id: 482, pl: "most", en: "bridge" },
  { id: 483, pl: "miasto", en: "city" },
  { id: 484, pl: "wieś", en: "village" },
  { id: 485, pl: "sklep", en: "shop" },
  { id: 486, pl: "restauracja", en: "restaurant" },
  { id: 487, pl: "hotel", en: "hotel" },
  { id: 488, pl: "szpital", en: "hospital" },
  { id: 489, pl: "apteka", en: "pharmacy" },
  { id: 490, pl: "policja", en: "police" },
  { id: 491, pl: "straż", en: "fire brigade" },
  { id: 492, pl: "bank", en: "bank" },
  { id: 493, pl: "kino", en: "cinema" },
  { id: 494, pl: "teatr", en: "theatre" },
  { id: 495, pl: "muzeum", en: "museum" },
  { id: 496, pl: "biblioteka", en: "library" },
  { id: 497, pl: "park", en: "park" },
  { id: 498, pl: "plac", en: "square" },
  { id: 499, pl: "ratusz", en: "town hall" },
  { id: 500, pl: "kościół", en: "church" }
];



const mediumWords: Word[] = [
    { id: 1, pl: "szczęśliwy", en: "happy" },
  { id: 2, pl: "smutny", en: "sad" },
  { id: 3, pl: "trudny", en: "difficult" },
  { id: 4, pl: "łatwy", en: "easy" },
  { id: 5, pl: "ważny", en: "important" },
  { id: 6, pl: "interesujący", en: "interesting" },
  { id: 7, pl: "nudny", en: "boring" },
  { id: 8, pl: "szybki", en: "fast" },
  { id: 9, pl: "wolny", en: "slow" },
  { id: 10, pl: "czysty", en: "clean" },
  { id: 11, pl: "brudny", en: "dirty" },
  { id: 12, pl: "głośny", en: "loud" },
  { id: 13, pl: "cichy", en: "quiet" },
  { id: 14, pl: "drogi", en: "expensive" },
  { id: 15, pl: "tani", en: "cheap" },
  { id: 16, pl: "głodny", en: "hungry" },
  { id: 17, pl: "spragniony", en: "thirsty" },
  { id: 18, pl: "silny", en: "strong" },
  { id: 19, pl: "słaby", en: "weak" },
  { id: 20, pl: "nowy", en: "new" },
  { id: 21, pl: "stary", en: "old" },
  { id: 22, pl: "wysoki", en: "tall" },
  { id: 23, pl: "niski", en: "short" },
  { id: 24, pl: "gorący", en: "hot" },
  { id: 25, pl: "zimny", en: "cold" },
  { id: 26, pl: "mokry", en: "wet" },
  { id: 27, pl: "suchy", en: "dry" },
  { id: 28, pl: "ciemny", en: "dark" },
  { id: 29, pl: "jasny", en: "bright" },
  { id: 30, pl: "zły", en: "bad" },
  { id: 31, pl: "dobry", en: "good" },
  { id: 32, pl: "piękny", en: "beautiful" },
  { id: 33, pl: "brzydki", en: "ugly" },
  { id: 34, pl: "gruby", en: "fat" },
  { id: 35, pl: "chudy", en: "thin" },
  { id: 36, pl: "mądry", en: "smart" },
  { id: 37, pl: "głupi", en: "stupid" },
  { id: 38, pl: "ciekawy", en: "curious" },
  { id: 39, pl: "bogaty", en: "rich" },
  { id: 40, pl: "biedny", en: "poor" },
  { id: 41, pl: "miły", en: "kind" },
  { id: 42, pl: "niegrzeczny", en: "rude" },
  { id: 43, pl: "silny", en: "powerful" },
  { id: 44, pl: "ważny", en: "significant" },
  { id: 45, pl: "spokojny", en: "calm" },
  { id: 46, pl: "zabawny", en: "funny" },
  { id: 47, pl: "tradycyjny", en: "traditional" },
  { id: 48, pl: "nowoczesny", en: "modern" },
  { id: 49, pl: "otwarty", en: "open" },
  { id: 50, pl: "zamknięty", en: "closed" },
  { id: 51, pl: "gorzki", en: "bitter" },
  { id: 52, pl: "słodki", en: "sweet" },
  { id: 53, pl: "kwaśny", en: "sour" },
  { id: 54, pl: "twardy", en: "hard" },
  { id: 55, pl: "miękki", en: "soft" },
  { id: 56, pl: "głęboki", en: "deep" },
  { id: 57, pl: "płytki", en: "shallow" },
  { id: 58, pl: "ważny", en: "crucial" },
  { id: 59, pl: "inteligentny", en: "intelligent" },
  { id: 60, pl: "szczery", en: "honest" },
  { id: 61, pl: "zajęty", en: "busy" },
  { id: 62, pl: "wolny", en: "free" },
  { id: 63, pl: "cienki", en: "thin" },
  { id: 64, pl: "gruby", en: "thick" },
  { id: 65, pl: "gładki", en: "smooth" },
  { id: 66, pl: "chropowaty", en: "rough" },
  { id: 67, pl: "głośny", en: "noisy" },
  { id: 68, pl: "cichy", en: "silent" },
  { id: 69, pl: "niebezpieczny", en: "dangerous" },
  { id: 70, pl: "bezpieczny", en: "safe" },
  { id: 71, pl: "ważny", en: "essential" },
  { id: 72, pl: "wspaniały", en: "wonderful" },
  { id: 73, pl: "poważny", en: "serious" },
  { id: 74, pl: "szybki", en: "rapid" },
  { id: 75, pl: "wolny", en: "slow" },
  { id: 76, pl: "świeży", en: "fresh" },
  { id: 77, pl: "stary", en: "ancient" },
  { id: 78, pl: "miękki", en: "tender" },
  { id: 79, pl: "mocny", en: "firm" },
  { id: 80, pl: "delikatny", en: "delicate" },
  { id: 81, pl: "ostry", en: "sharp" },
  { id: 82, pl: "tępy", en: "dull" },
  { id: 83, pl: "piękny", en: "lovely" },
  { id: 84, pl: "wesoły", en: "cheerful" },
  { id: 85, pl: "zmęczony", en: "tired" },
  { id: 86, pl: "zdrowy", en: "healthy" },
  { id: 87, pl: "chory", en: "sick" },
  { id: 88, pl: "zły", en: "angry" },
  { id: 89, pl: "spokojny", en: "peaceful" },
  { id: 90, pl: "silny", en: "robust" },
  { id: 91, pl: "mądry", en: "wise" },
  { id: 92, pl: "ciekawy", en: "inquisitive" },
  { id: 93, pl: "ważny", en: "vital" },
  { id: 94, pl: "pełny", en: "full" },
  { id: 95, pl: "pusty", en: "empty" },
  { id: 96, pl: "trudny", en: "complex" },
  { id: 97, pl: "prosty", en: "simple" },
  { id: 98, pl: "zimny", en: "chilly" },
  { id: 99, pl: "gorący", en: "warm" },
  { id: 100, pl: "dobry", en: "excellent" },
  { id: 101, pl: "zabawka", en: "toy" },
  { id: 102, pl: "książka", en: "book" },
  { id: 103, pl: "notatka", en: "note" },
  { id: 104, pl: "zeszyt", en: "notebook" },
  { id: 105, pl: "długopis", en: "pen" },
  { id: 106, pl: "ołówek", en: "pencil" },
  { id: 107, pl: "gumka", en: "eraser" },
  { id: 108, pl: "linijka", en: "ruler" },
  { id: 109, pl: "tablica", en: "board" },
  { id: 110, pl: "krzesło", en: "chair" },
  { id: 111, pl: "biurko", en: "desk" },
  { id: 112, pl: "szkoła", en: "school" },
  { id: 113, pl: "nauczyciel", en: "teacher" },
  { id: 114, pl: "uczeń", en: "student" },
  { id: 115, pl: "klasa", en: "classroom" },
  { id: 116, pl: "lekcja", en: "lesson" },
  { id: 117, pl: "egzamin", en: "exam" },
  { id: 118, pl: "zadanie", en: "task" },
  { id: 119, pl: "biblioteka", en: "library" },
  { id: 120, pl: "informatyka", en: "computer science" },
  { id: 121, pl: "matematyka", en: "math" },
  { id: 122, pl: "język", en: "language" },
  { id: 123, pl: "historia", en: "history" },
  { id: 124, pl: "geografia", en: "geography" },
  { id: 125, pl: "przyroda", en: "nature" },
  { id: 126, pl: "muzyka", en: "music" },
  { id: 127, pl: "plastyka", en: "art" },
  { id: 128, pl: "fizyka", en: "physics" },
  { id: 129, pl: "chemia", en: "chemistry" },
  { id: 130, pl: "biologia", en: "biology" },
  { id: 131, pl: "sport", en: "sport" },
  { id: 132, pl: "piłka", en: "ball" },
  { id: 133, pl: "rower", en: "bike" },
  { id: 134, pl: "basen", en: "swimming pool" },
  { id: 135, pl: "bieganie", en: "running" },
  { id: 136, pl: "gra", en: "game" },
  { id: 137, pl: "zespół", en: "team" },
  { id: 138, pl: "mecz", en: "match" },
  { id: 139, pl: "trening", en: "training" },
  { id: 140, pl: "kuchnia", en: "kitchen" },
  { id: 141, pl: "jedzenie", en: "food" },
  { id: 142, pl: "owoc", en: "fruit" },
  { id: 143, pl: "warzywo", en: "vegetable" },
  { id: 144, pl: "chleb", en: "bread" },
  { id: 145, pl: "ser", en: "cheese" },
  { id: 146, pl: "mięso", en: "meat" },
  { id: 147, pl: "ryba", en: "fish" },
  { id: 148, pl: "zupa", en: "soup" },
  { id: 149, pl: "sałatka", en: "salad" },
  { id: 150, pl: "napój", en: "drink" },
  { id: 151, pl: "woda", en: "water" },
  { id: 152, pl: "sok", en: "juice" },
  { id: 153, pl: "kawa", en: "coffee" },
  { id: 154, pl: "herbata", en: "tea" },
  { id: 155, pl: "cukier", en: "sugar" },
  { id: 156, pl: "sól", en: "salt" },
  { id: 157, pl: "pieprz", en: "pepper" },
  { id: 158, pl: "talerz", en: "plate" },
  { id: 159, pl: "widelec", en: "fork" },
  { id: 160, pl: "nóż", en: "knife" },
  { id: 161, pl: "łyżka", en: "spoon" },
  { id: 162, pl: "kubek", en: "cup" },
  { id: 163, pl: "szklanka", en: "glass" },
  { id: 164, pl: "garnek", en: "pot" },
  { id: 165, pl: "patelnia", en: "pan" },
  { id: 166, pl: "lodówka", en: "fridge" },
  { id: 167, pl: "kuchenka", en: "stove" },
  { id: 168, pl: "mikrofalówka", en: "microwave" },
  { id: 169, pl: "piec", en: "oven" },
  { id: 170, pl: "zmywarka", en: "dishwasher" },
  { id: 171, pl: "pralka", en: "washing machine" },
  { id: 172, pl: "sprzątanie", en: "cleaning" },
  { id: 173, pl: "odkurzacz", en: "vacuum cleaner" },
  { id: 174, pl: "miotła", en: "broom" },
  { id: 175, pl: "ścierka", en: "cloth" },
  { id: 176, pl: "kosz", en: "bin" },
  { id: 177, pl: "okno", en: "window" },
  { id: 178, pl: "drzwi", en: "door" },
  { id: 179, pl: "podłoga", en: "floor" },
  { id: 180, pl: "sufit", en: "ceiling" },
  { id: 181, pl: "ściana", en: "wall" },
  { id: 182, pl: "sufit", en: "roof" },
  { id: 183, pl: "mieszkanie", en: "apartment" },
  { id: 184, pl: "dom", en: "house" },
  { id: 185, pl: "ogród", en: "garden" },
  { id: 186, pl: "drzewo", en: "tree" },
  { id: 187, pl: "krzew", en: "bush" },
  { id: 188, pl: "kwiat", en: "flower" },
  { id: 189, pl: "trawa", en: "grass" },
  { id: 190, pl: "droga", en: "road" },
  { id: 191, pl: "ulica", en: "street" },
  { id: 192, pl: "samochód", en: "car" },
  { id: 193, pl: "rower", en: "bicycle" },
  { id: 194, pl: "autobus", en: "bus" },
  { id: 195, pl: "pociąg", en: "train" },
  { id: 196, pl: "samolot", en: "plane" },
  { id: 197, pl: "statek", en: "ship" },
  { id: 198, pl: "lotnisko", en: "airport" },
  { id: 199, pl: "dworzec", en: "station" },
  { id: 200, pl: "most", en: "bridge" },
  { id: 201, pl: "wynalazek", en: "invention" },
  { id: 202, pl: "eksperyment", en: "experiment" },
  { id: 203, pl: "teoria", en: "theory" },
  { id: 204, pl: "praktyka", en: "practice" },
  { id: 205, pl: "filozofia", en: "philosophy" },
  { id: 206, pl: "psychologia", en: "psychology" },
  { id: 207, pl: "kultura", en: "culture" },
  { id: 208, pl: "historia", en: "history" },
  { id: 209, pl: "społeczeństwo", en: "society" },
  { id: 210, pl: "polityka", en: "politics" },
  { id: 211, pl: "ekonomia", en: "economics" },
  { id: 212, pl: "zarządzanie", en: "management" },
  { id: 213, pl: "finanse", en: "finance" },
  { id: 214, pl: "technologia", en: "technology" },
  { id: 215, pl: "architektura", en: "architecture" },
  { id: 216, pl: "literatura", en: "literature" },
  { id: 217, pl: "przemysł", en: "industry" },
  { id: 218, pl: "rola", en: "role" },
  { id: 219, pl: "władza", en: "power" },
  { id: 220, pl: "prawo", en: "law" },
  { id: 221, pl: "wojna", en: "war" },
  { id: 222, pl: "pokój", en: "peace" },
  { id: 223, pl: "reformacja", en: "reformation" },
  { id: 224, pl: "rewolucja", en: "revolution" },
  { id: 225, pl: "demokracja", en: "democracy" },
  { id: 226, pl: "dyktatura", en: "dictatorship" },
  { id: 227, pl: "konstytucja", en: "constitution" },
  { id: 228, pl: "międzynarodowy", en: "international" },
  { id: 229, pl: "fundacja", en: "foundation" },
  { id: 230, pl: "projekt", en: "project" },
  { id: 231, pl: "badanie", en: "research" },
  { id: 232, pl: "analiza", en: "analysis" },
  { id: 233, pl: "dyskusja", en: "discussion" },
  { id: 234, pl: "argument", en: "argument" },
  { id: 235, pl: "konflikt", en: "conflict" },
  { id: 236, pl: "strategia", en: "strategy" },
  { id: 237, pl: "taktyka", en: "tactic" },
  { id: 238, pl: "prawość", en: "justice" },
  { id: 239, pl: "sprawiedliwość", en: "fairness" },
  { id: 240, pl: "wolność", en: "freedom" },
  { id: 241, pl: "odpowiedzialność", en: "responsibility" },
  { id: 242, pl: "ryzyko", en: "risk" },
  { id: 243, pl: "zagrożenie", en: "threat" },
  { id: 244, pl: "bezpieczeństwo", en: "security" },
  { id: 245, pl: "zagadka", en: "mystery" },
  { id: 246, pl: "przyczyna", en: "cause" },
  { id: 247, pl: "skutek", en: "effect" },
  { id: 248, pl: "wzór", en: "pattern" },
  { id: 249, pl: "model", en: "model" },
  { id: 250, pl: "schemat", en: "scheme" },
  { id: 251, pl: "idea", en: "idea" },
  { id: 252, pl: "koncepcja", en: "concept" },
  { id: 253, pl: "teza", en: "thesis" },
  { id: 254, pl: "hipoteza", en: "hypothesis" },
  { id: 255, pl: "fakt", en: "fact" },
  { id: 256, pl: "dowód", en: "evidence" },
  { id: 257, pl: "argumentacja", en: "argumentation" },
  { id: 258, pl: "konkluzja", en: "conclusion" },
  { id: 259, pl: "wynik", en: "result" },
  { id: 260, pl: "przypadek", en: "case" },
  { id: 261, pl: "sytuacja", en: "situation" },
  { id: 262, pl: "stan", en: "state" },
  { id: 263, pl: "proces", en: "process" },
  { id: 264, pl: "metoda", en: "method" },
  { id: 265, pl: "technika", en: "technique" },
  { id: 266, pl: "narzędzie", en: "tool" },
  { id: 267, pl: "mechanizm", en: "mechanism" },
  { id: 268, pl: "system", en: "system" },
  { id: 269, pl: "organizacja", en: "organization" },
  { id: 270, pl: "instytucja", en: "institution" },
  { id: 271, pl: "firma", en: "company" },
  { id: 272, pl: "biznes", en: "business" },
  { id: 273, pl: "handel", en: "trade" },
  { id: 274, pl: "rynki", en: "markets" },
  { id: 275, pl: "produkt", en: "product" },
  { id: 276, pl: "usługa", en: "service" },
  { id: 277, pl: "zysk", en: "profit" },
  { id: 278, pl: "strata", en: "loss" },
  { id: 279, pl: "konkurencja", en: "competition" },
  { id: 280, pl: "klient", en: "client" },
  { id: 281, pl: "partner", en: "partner" },
  { id: 282, pl: "projekt", en: "project" },
  { id: 283, pl: "cel", en: "goal" },
  { id: 284, pl: "plan", en: "plan" },
  { id: 285, pl: "zadanie", en: "task" },
  { id: 286, pl: "termin", en: "deadline" },
  { id: 287, pl: "harmonogram", en: "schedule" },
  { id: 288, pl: "spotkanie", en: "meeting" },
  { id: 289, pl: "dyskusja", en: "discussion" },
  { id: 290, pl: "decyzja", en: "decision" },
  { id: 291, pl: "problem", en: "problem" },
  { id: 292, pl: "rozwiązanie", en: "solution" },
  { id: 293, pl: "pomysł", en: "idea" },
  { id: 294, pl: "wiedza", en: "knowledge" },
  { id: 295, pl: "doświadczenie", en: "experience" },
  { id: 296, pl: "umiejętność", en: "skill" },
  { id: 297, pl: "kompetencja", en: "competence" },
  { id: 298, pl: "talent", en: "talent" },
  { id: 299, pl: "edukacja", en: "education" },
  { id: 300, pl: "nauka", en: "science" },
  { id: 301, pl: "inwestycja", en: "investment" },
  { id: 302, pl: "strategia", en: "strategy" },
  { id: 303, pl: "innowacja", en: "innovation" },
  { id: 304, pl: "transformacja", en: "transformation" },
  { id: 305, pl: "adaptacja", en: "adaptation" },
  { id: 306, pl: "integracja", en: "integration" },
  { id: 307, pl: "koordynacja", en: "coordination" },
  { id: 308, pl: "negocjacje", en: "negotiations" },
  { id: 309, pl: "komunikacja", en: "communication" },
  { id: 310, pl: "przywództwo", en: "leadership" },
  { id: 311, pl: "motywacja", en: "motivation" },
  { id: 312, pl: "zaangażowanie", en: "engagement" },
  { id: 313, pl: "kreatywność", en: "creativity" },
  { id: 314, pl: "rozwój", en: "development" },
  { id: 315, pl: "wyzwanie", en: "challenge" },
  { id: 316, pl: "kompetencja", en: "competence" },
  { id: 317, pl: "ocena", en: "evaluation" },
  { id: 318, pl: "efektywność", en: "efficiency" },
  { id: 319, pl: "produktywność", en: "productivity" },
  { id: 320, pl: "projektowanie", en: "design" },
  { id: 321, pl: "realizacja", en: "implementation" },
  { id: 322, pl: "monitorowanie", en: "monitoring" },
  { id: 323, pl: "analiza", en: "analysis" },
  { id: 324, pl: "kontrola", en: "control" },
  { id: 325, pl: "rynek", en: "market" },
  { id: 326, pl: "klient", en: "customer" },
  { id: 327, pl: "konkurencja", en: "competition" },
  { id: 328, pl: "segmentacja", en: "segmentation" },
  { id: 329, pl: "strategia marketingowa", en: "marketing strategy" },
  { id: 330, pl: "produkt", en: "product" },
  { id: 331, pl: "usługa", en: "service" },
  { id: 332, pl: "reklama", en: "advertisement" },
  { id: 333, pl: "promocja", en: "promotion" },
  { id: 334, pl: "sprzedaż", en: "sales" },
  { id: 335, pl: "dystrybucja", en: "distribution" },
  { id: 336, pl: "logistyka", en: "logistics" },
  { id: 337, pl: "łańcuch dostaw", en: "supply chain" },
  { id: 338, pl: "magazyn", en: "warehouse" },
  { id: 339, pl: "produkcja", en: "production" },
  { id: 340, pl: "jakość", en: "quality" },
  { id: 341, pl: "certyfikat", en: "certificate" },
  { id: 342, pl: "standard", en: "standard" },
  { id: 343, pl: "norma", en: "norm" },
  { id: 344, pl: "procedura", en: "procedure" },
  { id: 345, pl: "instrukcja", en: "instruction" },
  { id: 346, pl: "dokumentacja", en: "documentation" },
  { id: 347, pl: "raport", en: "report" },
  { id: 348, pl: "analiza ryzyka", en: "risk analysis" },
  { id: 349, pl: "zagrożenie", en: "threat" },
  { id: 350, pl: "szansa", en: "opportunity" },
  { id: 351, pl: "kryzys", en: "crisis" },
  { id: 352, pl: "awaria", en: "failure" },
  { id: 353, pl: "naprawa", en: "repair" },
  { id: 354, pl: "utrzymanie", en: "maintenance" },
  { id: 355, pl: "bezpieczeństwo", en: "safety" },
  { id: 356, pl: "ochrona", en: "protection" },
  { id: 357, pl: "ochrona środowiska", en: "environmental protection" },
  { id: 358, pl: "ekologia", en: "ecology" },
  { id: 359, pl: "energia", en: "energy" },
  { id: 360, pl: "zrównoważony rozwój", en: "sustainable development" },
  { id: 361, pl: "zasoby", en: "resources" },
  { id: 362, pl: "kapitał", en: "capital" },
  { id: 363, pl: "inwestor", en: "investor" },
  { id: 364, pl: "akcje", en: "shares" },
  { id: 365, pl: "rynek kapitałowy", en: "capital market" },
  { id: 366, pl: "bank", en: "bank" },
  { id: 367, pl: "kredyt", en: "loan" },
  { id: 368, pl: "depozyt", en: "deposit" },
  { id: 369, pl: "oprocentowanie", en: "interest rate" },
  { id: 370, pl: "budżet", en: "budget" },
  { id: 371, pl: "koszt", en: "cost" },
  { id: 372, pl: "przychód", en: "revenue" },
  { id: 373, pl: "dochód", en: "income" },
  { id: 374, pl: "zysk netto", en: "net profit" },
  { id: 375, pl: "strata netto", en: "net loss" },
  { id: 376, pl: "rachunek", en: "account" },
  { id: 377, pl: "faktura", en: "invoice" },
  { id: 378, pl: "płatność", en: "payment" },
  { id: 379, pl: "rachunkowość", en: "accounting" },
  { id: 380, pl: "audyt", en: "audit" },
  { id: 381, pl: "prawo pracy", en: "labor law" },
  { id: 382, pl: "umowa", en: "contract" },
  { id: 383, pl: "zarząd", en: "management board" },
  { id: 384, pl: "zarządca", en: "manager" },
  { id: 385, pl: "pracownik", en: "employee" },
  { id: 386, pl: "etat", en: "job position" },
  { id: 387, pl: "urlop", en: "vacation" },
  { id: 388, pl: "szkolenie", en: "training" },
  { id: 389, pl: "rozwój kariery", en: "career development" },
  { id: 390, pl: "ocena pracownika", en: "employee evaluation" },
  { id: 391, pl: "motywacja", en: "motivation" },
  { id: 392, pl: "premia", en: "bonus" },
  { id: 393, pl: "wynagrodzenie", en: "salary" },
  { id: 394, pl: "świadczenia", en: "benefits" },
  { id: 395, pl: "rekrutacja", en: "recruitment" },
  { id: 396, pl: "zwolnienie", en: "dismissal" },
  { id: 397, pl: "pracodawca", en: "employer" },
  { id: 398, pl: "przedsiębiorstwo", en: "enterprise" },
  { id: 399, pl: "firma", en: "company" },
  { id: 400, pl: "korporacja", en: "corporation" },
  { id: 401, pl: "konsumpcja", en: "consumption" },
  { id: 402, pl: "produkcja", en: "production" },
  { id: 403, pl: "dystrybucja", en: "distribution" },
  { id: 404, pl: "handel zagraniczny", en: "foreign trade" },
  { id: 405, pl: "eksport", en: "export" },
  { id: 406, pl: "import", en: "import" },
  { id: 407, pl: "budżet państwa", en: "state budget" },
  { id: 408, pl: "deficyt", en: "deficit" },
  { id: 409, pl: "nadwyżka", en: "surplus" },
  { id: 410, pl: "inflacja", en: "inflation" },
  { id: 411, pl: "deflacja", en: "deflation" },
  { id: 412, pl: "bezrobocie", en: "unemployment" },
  { id: 413, pl: "polityka monetarna", en: "monetary policy" },
  { id: 414, pl: "polityka fiskalna", en: "fiscal policy" },
  { id: 415, pl: "bank centralny", en: "central bank" },
  { id: 416, pl: "stopa procentowa", en: "interest rate" },
  { id: 417, pl: "kredyt hipoteczny", en: "mortgage" },
  { id: 418, pl: "ubezpieczenie", en: "insurance" },
  { id: 419, pl: "emerytura", en: "pension" },
  { id: 420, pl: "system emerytalny", en: "pension system" },
  { id: 421, pl: "demografia", en: "demography" },
  { id: 422, pl: "migracja", en: "migration" },
  { id: 423, pl: "urbanizacja", en: "urbanization" },
  { id: 424, pl: "globalizacja", en: "globalization" },
  { id: 425, pl: "zrównoważony rozwój", en: "sustainable development" },
  { id: 426, pl: "energia odnawialna", en: "renewable energy" },
  { id: 427, pl: "źródła energii", en: "energy sources" },
  { id: 428, pl: "zmiany klimatyczne", en: "climate change" },
  { id: 429, pl: "ochrona środowiska", en: "environmental protection" },
  { id: 430, pl: "bioróżnorodność", en: "biodiversity" },
  { id: 431, pl: "ekosystem", en: "ecosystem" },
  { id: 432, pl: "recykling", en: "recycling" },
  { id: 433, pl: "odpady", en: "waste" },
  { id: 434, pl: "zagrożone gatunki", en: "endangered species" },
  { id: 435, pl: "parlament", en: "parliament" },
  { id: 436, pl: "rząd", en: "government" },
  { id: 437, pl: "ministerstwo", en: "ministry" },
  { id: 438, pl: "senat", en: "senate" },
  { id: 439, pl: "prezydent", en: "president" },
  { id: 440, pl: "premier", en: "prime minister" },
  { id: 441, pl: "wojsko", en: "military" },
  { id: 442, pl: "policja", en: "police" },
  { id: 443, pl: "sąd", en: "court" },
  { id: 444, pl: "wyrok", en: "verdict" },
  { id: 445, pl: "prawo", en: "law" },
  { id: 446, pl: "konstytucja", en: "constitution" },
  { id: 447, pl: "prawo karne", en: "criminal law" },
  { id: 448, pl: "prawo cywilne", en: "civil law" },
  { id: 449, pl: "adwokat", en: "lawyer" },
  { id: 450, pl: "prokurator", en: "prosecutor" },
  { id: 451, pl: "świadek", en: "witness" },
  { id: 452, pl: "przestępstwo", en: "crime" },
  { id: 453, pl: "kara", en: "penalty" },
  { id: 454, pl: "więzienie", en: "prison" },
  { id: 455, pl: "amnestia", en: "amnesty" },
  { id: 456, pl: "prawa człowieka", en: "human rights" },
  { id: 457, pl: "wolność słowa", en: "freedom of speech" },
  { id: 458, pl: "demokracja", en: "democracy" },
  { id: 459, pl: "dyktatura", en: "dictatorship" },
  { id: 460, pl: "wolność", en: "freedom" },
  { id: 461, pl: "praworządność", en: "rule of law" },
  { id: 462, pl: "integracja europejska", en: "European integration" },
  { id: 463, pl: "Unia Europejska", en: "European Union" },
  { id: 464, pl: "NATO", en: "NATO" },
  { id: 465, pl: "ONZ", en: "UN" },
  { id: 466, pl: "wojna", en: "war" },
  { id: 467, pl: "pokój", en: "peace" },
  { id: 468, pl: "konflikt", en: "conflict" },
  { id: 469, pl: "dyplomacja", en: "diplomacy" },
  { id: 470, pl: "negocjacje", en: "negotiations" },
  { id: 471, pl: "sojusz", en: "alliance" },
  { id: 472, pl: "atak", en: "attack" },
  { id: 473, pl: "obrona", en: "defense" },
  { id: 474, pl: "broń", en: "weapon" },
  { id: 475, pl: "wojskowy", en: "military (adj)" },
  { id: 476, pl: "atak terrorystyczny", en: "terrorist attack" },
  { id: 477, pl: "terroryzm", en: "terrorism" },
  { id: 478, pl: "atak cybernetyczny", en: "cyber attack" },
  { id: 479, pl: "bezpieczeństwo narodowe", en: "national security" },
  { id: 480, pl: "wywiad", en: "intelligence" },
  { id: 481, pl: "szpiegostwo", en: "espionage" },
  { id: 482, pl: "kontrwywiad", en: "counterintelligence" },
  { id: 483, pl: "technologia informacyjna", en: "information technology" },
  { id: 484, pl: "komputer", en: "computer" },
  { id: 485, pl: "oprogramowanie", en: "software" },
  { id: 486, pl: "sprzęt komputerowy", en: "hardware" },
  { id: 487, pl: "internet", en: "internet" },
  { id: 488, pl: "sieć", en: "network" },
  { id: 489, pl: "strona internetowa", en: "website" },
  { id: 490, pl: "aplikacja", en: "application" },
  { id: 491, pl: "baz danych", en: "database" },
  { id: 492, pl: "programowanie", en: "programming" },
  { id: 493, pl: "kod", en: "code" },
  { id: 494, pl: "algorytm", en: "algorithm" },
  { id: 495, pl: "sztuczna inteligencja", en: "artificial intelligence" },
  { id: 496, pl: "uczenie maszynowe", en: "machine learning" },
  { id: 497, pl: "robotyka", en: "robotics" },
  { id: 498, pl: "automatyzacja", en: "automation" },
  { id: 499, pl: "cyberbezpieczeństwo", en: "cybersecurity" },
  { id: 500, pl: "technologia blockchain", en: "blockchain technology" }
];

const hardWords: Word[] = [
  { id: 1, pl: "abstrakcja", en: "abstraction" },
  { id: 2, pl: "akomodacja", en: "accommodation" },
  { id: 3, pl: "adekwatny", en: "adequate" },
  { id: 4, pl: "afiliacja", en: "affiliation" },
  { id: 5, pl: "agregacja", en: "aggregation" },
  { id: 6, pl: "aneksja", en: "annexation" },
  { id: 7, pl: "antycypacja", en: "anticipation" },
  { id: 8, pl: "aplikacja", en: "application" },
  { id: 9, pl: "aranżacja", en: "arrangement" },
  { id: 10, pl: "asymetria", en: "asymmetry" },
  { id: 11, pl: "atrybut", en: "attribute" },
  { id: 12, pl: "autentyczność", en: "authenticity" },
  { id: 13, pl: "benevolencja", en: "benevolence" },
  { id: 14, pl: "łagodność", en: "benignity" },
  { id: 15, pl: "bilateralny", en: "bilateral" },
  { id: 16, pl: "cynizm", en: "cynicism" },
  { id: 17, pl: "dekonstrukcja", en: "deconstruction" },
  { id: 18, pl: "determinacja", en: "determination" },
  { id: 19, pl: "dyskrecja", en: "discretion" },
  { id: 20, pl: "dyspersja", en: "dispersion" },
  { id: 21, pl: "ekstrapolacja", en: "extrapolation" },
  { id: 22, pl: "federacja", en: "federation" },
  { id: 23, pl: "filantropia", en: "philanthropy" },
  { id: 24, pl: "frakcja", en: "faction" },
  { id: 25, pl: "fundamentalny", en: "fundamental" },
  { id: 26, pl: "gentryfikacja", en: "gentrification" },
  { id: 27, pl: "hierarchia", en: "hierarchy" },
  { id: 28, pl: "ikonografia", en: "iconography" },
  { id: 29, pl: "impet", en: "momentum" },
  { id: 30, pl: "indoktrynacja", en: "indoctrination" },
  { id: 31, pl: "inercja", en: "inertia" },
  { id: 32, pl: "infrastruktura", en: "infrastructure" },
  { id: 33, pl: "innowacyjność", en: "innovativeness" },
  { id: 34, pl: "inteligencja emocjonalna", en: "emotional intelligence" },
  { id: 35, pl: "interferencja", en: "interference" },
  { id: 36, pl: "interwencja", en: "intervention" },
  { id: 37, pl: "inwersja", en: "inversion" },
  { id: 38, pl: "inwigilacja", en: "surveillance" },
  { id: 39, pl: "irracjonalność", en: "irrationality" },
  { id: 40, pl: "kalibracja", en: "calibration" },
  { id: 41, pl: "kategoria", en: "category" },
  { id: 42, pl: "klaustrofobia", en: "claustrophobia" },
  { id: 43, pl: "koherencja", en: "coherence" },
  { id: 44, pl: "kompilacja", en: "compilation" },
  { id: 45, pl: "kompleksowość", en: "complexity" },
  { id: 46, pl: "konsekwencja", en: "consequence" },
  { id: 47, pl: "konsensus", en: "consensus" },
  { id: 48, pl: "kontemplacja", en: "contemplation" },
  { id: 49, pl: "konwergencja", en: "convergence" },
  { id: 50, pl: "koordynacja", en: "coordination" },
  { id: 51, pl: "korekta", en: "correction" },
  { id: 52, pl: "kryterium", en: "criterion" },
  { id: 53, pl: "kryptografia", en: "cryptography" },
  { id: 54, pl: "kulminacja", en: "culmination" },
  { id: 55, pl: "kulturowy", en: "cultural" },
  { id: 56, pl: "legitymizacja", en: "legitimization" },
  { id: 57, pl: "linia demarkacyjna", en: "demarcation line" },
  { id: 58, pl: "logistyka", en: "logistics" },
  { id: 59, pl: "manipulacja", en: "manipulation" },
  { id: 60, pl: "medytacja", en: "meditation" },
  { id: 61, pl: "mikroekonomia", en: "microeconomics" },
  { id: 62, pl: "migracja", en: "migration" },
  { id: 63, pl: "minimalizm", en: "minimalism" },
  { id: 64, pl: "modalność", en: "modality" },
  { id: 65, pl: "monopol", en: "monopoly" },
  { id: 66, pl: "motywacja", en: "motivation" },
  { id: 67, pl: "narracja", en: "narrative" },
  { id: 68, pl: "neutralność", en: "neutrality" },
  { id: 69, pl: "nomenklatura", en: "nomenclature" },
  { id: 70, pl: "normatywny", en: "normative" },
  { id: 71, pl: "obligacja", en: "bond" },
  { id: 72, pl: "obserwacja", en: "observation" },
  { id: 73, pl: "odporność", en: "resilience" },
  { id: 74, pl: "operacja", en: "operation" },
  { id: 75, pl: "optymalizacja", en: "optimization" },
  { id: 76, pl: "organizacja", en: "organization" },
  { id: 77, pl: "orientacja", en: "orientation" },
  { id: 78, pl: "paradygmat", en: "paradigm" },
  { id: 79, pl: "parlamentaryzm", en: "parliamentarism" },
  { id: 80, pl: "partycypacja", en: "participation" },
  { id: 81, pl: "perspektywa", en: "perspective" },
  { id: 82, pl: "planowanie", en: "planning" },
  { id: 83, pl: "platforma", en: "platform" },
  { id: 84, pl: "polaryzacja", en: "polarization" },
  { id: 85, pl: "polityka", en: "policy" },
  { id: 86, pl: "populacja", en: "population" },
  { id: 87, pl: "porozumienie", en: "agreement" },
  { id: 88, pl: "potencjał", en: "potential" },
  { id: 89, pl: "praktyka", en: "practice" },
  { id: 90, pl: "precedens", en: "precedent" },
  { id: 91, pl: "precyzja", en: "precision" },
  { id: 92, pl: "preferencja", en: "preference" },
  { id: 93, pl: "premisa", en: "premise" },
  { id: 94, pl: "presja", en: "pressure" },
  { id: 95, pl: "prestiż", en: "prestige" },
  { id: 96, pl: "przekształcenie", en: "transformation" },
  { id: 97, pl: "przyczyna", en: "cause" },
  { id: 98, pl: "przywództwo", en: "leadership" },
  { id: 99, pl: "racjonalność", en: "rationality" },
  { id: 100, pl: "redukcja", en: "reduction" },
    { id: 101, pl: "replikacja", en: "replication" },
  { id: 102, pl: "rezyliencja", en: "resilience" },
  { id: 103, pl: "rewizja", en: "revision" },
  { id: 104, pl: "sekularyzm", en: "secularism" },
  { id: 105, pl: "sekwencja", en: "sequence" },
  { id: 106, pl: "seminarium", en: "seminar" },
  { id: 107, pl: "separacja", en: "separation" },
  { id: 108, pl: "sensoryczny", en: "sensory" },
  { id: 109, pl: "sentencja", en: "sentence" },
  { id: 110, pl: "separatysta", en: "separatist" },
  { id: 111, pl: "serendypia", en: "serendipity" },
  { id: 112, pl: "sferyczny", en: "spherical" },
  { id: 113, pl: "strategia", en: "strategy" },
  { id: 114, pl: "struktura", en: "structure" },
  { id: 115, pl: "substancja", en: "substance" },
  { id: 116, pl: "subtelność", en: "subtlety" },
  { id: 117, pl: "subwencja", en: "subvention" },
  { id: 118, pl: "sukcesja", en: "succession" },
  { id: 119, pl: "suma", en: "sum" },
  { id: 120, pl: "symetria", en: "symmetry" },
  { id: 121, pl: "symbioza", en: "symbiosis" },
  { id: 122, pl: "symbolika", en: "symbolism" },
  { id: 123, pl: "sympatia", en: "sympathy" },
  { id: 124, pl: "synteza", en: "synthesis" },
  { id: 125, pl: "systematyczność", en: "systematicity" },
  { id: 126, pl: "taksonomia", en: "taxonomy" },
  { id: 127, pl: "technologia", en: "technology" },
  { id: 128, pl: "teoretyczny", en: "theoretical" },
  { id: 129, pl: "testament", en: "testament" },
  { id: 130, pl: "tolerancja", en: "tolerance" },
  { id: 131, pl: "transcendencja", en: "transcendence" },
  { id: 132, pl: "transformacja", en: "transformation" },
  { id: 133, pl: "transparentność", en: "transparency" },
  { id: 134, pl: "trauma", en: "trauma" },
  { id: 135, pl: "trend", en: "trend" },
  { id: 136, pl: "trwanie", en: "duration" },
  { id: 137, pl: "typologia", en: "typology" },
  { id: 138, pl: "unikalność", en: "uniqueness" },
  { id: 139, pl: "unifikacja", en: "unification" },
  { id: 140, pl: "urbanistyka", en: "urban planning" },
  { id: 141, pl: "ustawodawstwo", en: "legislation" },
  { id: 142, pl: "utrwalanie", en: "consolidation" },
  { id: 143, pl: "uzasadnienie", en: "justification" },
  { id: 144, pl: "uwspółcześnienie", en: "modernization" },
  { id: 145, pl: "waloryzacja", en: "indexation" },
  { id: 146, pl: "wariant", en: "variant" },
  { id: 147, pl: "wydajność", en: "efficiency" },
  { id: 148, pl: "weryfikacja", en: "verification" },
  { id: 149, pl: "wieloznaczność", en: "ambiguity" },
  { id: 150, pl: "wielowymiarowość", en: "multidimensionality" },
  { id: 151, pl: "winieta", en: "vignette" },
  { id: 152, pl: "wizualizacja", en: "visualization" },
  { id: 153, pl: "wolumen", en: "volume" },
  { id: 154, pl: "wrażliwość", en: "sensitivity" },
  { id: 155, pl: "wspólnota", en: "community" },
  { id: 156, pl: "współzależność", en: "interdependence" },
  { id: 157, pl: "współczesność", en: "contemporary times" },
  { id: 158, pl: "współpraca", en: "cooperation" },
  { id: 159, pl: "wstrząs", en: "shock" },
  { id: 160, pl: "wstydliwość", en: "shyness" },
  { id: 161, pl: "wybitny", en: "outstanding" },
  { id: 162, pl: "wykorzystanie", en: "utilization" },
  { id: 163, pl: "wypaczenie", en: "distortion" },
  { id: 164, pl: "wytwórczość", en: "production" },
  { id: 165, pl: "wyzwolenie", en: "liberation" },
  { id: 166, pl: "wyznanie", en: "confession" },
  { id: 167, pl: "wyzwolenie", en: "emancipation" },
  { id: 168, pl: "zagrożenie", en: "threat" },
  { id: 169, pl: "założenie", en: "assumption" },
  { id: 170, pl: "zaostrzanie", en: "tightening" },
  { id: 171, pl: "zasada", en: "principle" },
  { id: 172, pl: "zasób", en: "resource" },
  { id: 173, pl: "zastrzeżenie", en: "reservation" },
  { id: 174, pl: "zastosowanie", en: "application" },
  { id: 175, pl: "zatrzymanie", en: "detention" },
  { id: 176, pl: "zatwierdzenie", en: "approval" },
  { id: 177, pl: "zazdrość", en: "jealousy" },
  { id: 178, pl: "zderzenie", en: "collision" },
  { id: 179, pl: "zdolność", en: "capability" },
  { id: 180, pl: "zespół", en: "team" },
  { id: 181, pl: "zjawisko", en: "phenomenon" },
  { id: 182, pl: "znaczenie", en: "meaning" },
  { id: 183, pl: "znajomość", en: "familiarity" },
  { id: 184, pl: "zobowiązanie", en: "commitment" },
  { id: 185, pl: "zrównoważenie", en: "balance" },
  { id: 186, pl: "związek", en: "relationship" },
  { id: 187, pl: "zwrot", en: "return" },
  { id: 188, pl: "żywotność", en: "viability" },
  { id: 189, pl: "ząb", en: "tooth" },
  { id: 190, pl: "źródło", en: "source" },
  { id: 191, pl: "żargon", en: "jargon" },
  { id: 192, pl: "żmudny", en: "arduous" },
  { id: 193, pl: "żółw", en: "turtle" },
  { id: 194, pl: "żywność", en: "food" },
  { id: 195, pl: "zaawansowany", en: "advanced" },
  { id: 196, pl: "zaleta", en: "advantage" },
  { id: 197, pl: "załącznik", en: "attachment" },
  { id: 198, pl: "zamieszanie", en: "confusion" },
  { id: 199, pl: "zasięg", en: "range" },
  { id: 200, pl: "zasada", en: "rule" },
  { id: 201, pl: "aberracja", en: "aberration" },
  { id: 202, pl: "akceptacja", en: "acceptance" },
  { id: 203, pl: "aklimatyzacja", en: "acclimatization" },
  { id: 204, pl: "akredytacja", en: "accreditation" },
  { id: 205, pl: "adaptacja", en: "adaptation" },
  { id: 206, pl: "adekwatność", en: "adequacy" },
  { id: 207, pl: "administracja", en: "administration" },
  { id: 208, pl: "adopcja", en: "adoption" },
  { id: 209, pl: "afirmacja", en: "affirmation" },
  { id: 210, pl: "agencja", en: "agency" },
  { id: 211, pl: "aglomeracja", en: "agglomeration" },
  { id: 212, pl: "agresja", en: "aggression" },
  { id: 213, pl: "alegoria", en: "allegory" },
  { id: 214, pl: "alternatywa", en: "alternative" },
  { id: 215, pl: "amplituda", en: "amplitude" },
  { id: 216, pl: "analiza", en: "analysis" },
  { id: 217, pl: "anatomia", en: "anatomy" },
  { id: 218, pl: "aneks", en: "annex" },
  { id: 219, pl: "animacja", en: "animation" },
  { id: 220, pl: "anomalia", en: "anomaly" },
  { id: 221, pl: "antycypacja", en: "anticipation" },
  { id: 222, pl: "aparat", en: "apparatus" },
  { id: 223, pl: "apetyt", en: "appetite" },
  { id: 224, pl: "aplikant", en: "applicant" },
  { id: 225, pl: "architektura", en: "architecture" },
  { id: 226, pl: "archetyp", en: "archetype" },
  { id: 227, pl: "argumentacja", en: "argumentation" },
  { id: 228, pl: "arystokracja", en: "aristocracy" },
  { id: 229, pl: "artykulacja", en: "articulation" },
  { id: 230, pl: "aspekt", en: "aspect" },
  { id: 231, pl: "asymetria", en: "asymmetry" },
  { id: 232, pl: "atmosfera", en: "atmosphere" },
  { id: 233, pl: "atrakcja", en: "attraction" },
  { id: 234, pl: "audytorium", en: "auditorium" },
  { id: 235, pl: "autentyczność", en: "authenticity" },
  { id: 236, pl: "autorytet", en: "authority" },
  { id: 237, pl: "awans", en: "promotion" },
  { id: 238, pl: "badanie", en: "investigation" },
  { id: 239, pl: "balans", en: "balance" },
  { id: 240, pl: "bariera", en: "barrier" },
  { id: 241, pl: "baza", en: "base" },
  { id: 242, pl: "beneficjent", en: "beneficiary" },
  { id: 243, pl: "biografia", en: "biography" },
  { id: 244, pl: "biomasa", en: "biomass" },
  { id: 245, pl: "biopsja", en: "biopsy" },
  { id: 246, pl: "biotechnologia", en: "biotechnology" },
  { id: 247, pl: "biznes", en: "business" },
  { id: 248, pl: "blokada", en: "blockade" },
  { id: 249, pl: "bohater", en: "hero" },
  { id: 250, pl: "brak", en: "lack" },
  { id: 251, pl: "brzemię", en: "burden" },
  { id: 252, pl: "budżet", en: "budget" },
  { id: 253, pl: "budowa", en: "construction" },
  { id: 254, pl: "bycie", en: "being" },
  { id: 255, pl: "calość", en: "whole" },
  { id: 256, pl: "caloroczny", en: "year-round" },
  { id: 257, pl: "cena", en: "price" },
  { id: 258, pl: "centrum", en: "center" },
  { id: 259, pl: "cecha", en: "feature" },
  { id: 260, pl: "charakterystyka", en: "characteristics" },
  { id: 261, pl: "charakter", en: "character" },
  { id: 262, pl: "chemia", en: "chemistry" },
  { id: 263, pl: "chirurgia", en: "surgery" },
  { id: 264, pl: "choroba", en: "disease" },
  { id: 265, pl: "chronologia", en: "chronology" },
  { id: 266, pl: "ciężar", en: "weight" },
  { id: 267, pl: "ciepło", en: "heat" },
  { id: 268, pl: "ciekawość", en: "curiosity" },
  { id: 269, pl: "ciśnienie", en: "pressure" },
  { id: 270, pl: "cnota", en: "virtue" },
  { id: 271, pl: "cofnąć", en: "withdraw" },
  { id: 272, pl: "codzienność", en: "everyday life" },
  { id: 273, pl: "codzienny", en: "daily" },
  { id: 274, pl: "część", en: "part" },
  { id: 275, pl: "czystość", en: "purity" },
  { id: 276, pl: "czytelność", en: "legibility" },
  { id: 277, pl: "cynizm", en: "cynicism" },
  { id: 278, pl: "cytologia", en: "cytology" },
  { id: 279, pl: "dane", en: "data" },
  { id: 280, pl: "dar", en: "gift" },
  { id: 281, pl: "debatować", en: "debate" },
  { id: 282, pl: "decyzja", en: "decision" },
  { id: 283, pl: "definicja", en: "definition" },
  { id: 284, pl: "delegacja", en: "delegation" },
  { id: 285, pl: "demokracja", en: "democracy" },
  { id: 286, pl: "demografia", en: "demography" },
  { id: 287, pl: "denominacja", en: "denomination" },
  { id: 288, pl: "depresja", en: "depression" },
  { id: 289, pl: "destrukcja", en: "destruction" },
  { id: 290, pl: "determinant", en: "determinant" },
  { id: 291, pl: "detoks", en: "detox" },
  { id: 292, pl: "dialog", en: "dialogue" },
  { id: 293, pl: "diament", en: "diamond" },
  { id: 294, pl: "dieta", en: "diet" },
  { id: 295, pl: "dyscyplina", en: "discipline" },
  { id: 296, pl: "dyskurs", en: "discourse" },
  { id: 297, pl: "dysproporcja", en: "disproportion" },
  { id: 298, pl: "dywersja", en: "diversion" },
  { id: 299, pl: "dyzenteria", en: "dysentery" },
  { id: 300, pl: "edukacja", en: "education" },
    { id: 301, pl: "efemeryczny", en: "ephemeral" },
  { id: 302, pl: "efektywność", en: "efficiency" },
  { id: 303, pl: "efuzja", en: "effusion" },
  { id: 304, pl: "egzamin", en: "exam" },
  { id: 305, pl: "egzekucja", en: "execution" },
  { id: 306, pl: "eklektyzm", en: "eclecticism" },
  { id: 307, pl: "ekologia", en: "ecology" },
  { id: 308, pl: "ekonomia", en: "economy" },
  { id: 309, pl: "ekspansja", en: "expansion" },
  { id: 310, pl: "ekspresja", en: "expression" },
  { id: 311, pl: "eksperyment", en: "experiment" },
  { id: 312, pl: "eksplozja", en: "explosion" },
  { id: 313, pl: "eksport", en: "export" },
  { id: 314, pl: "ekstaza", en: "ecstasy" },
  { id: 315, pl: "eksterminacja", en: "extermination" },
  { id: 316, pl: "elektryczność", en: "electricity" },
  { id: 317, pl: "element", en: "element" },
  { id: 318, pl: "elita", en: "elite" },
  { id: 319, pl: "elokwencja", en: "eloquence" },
  { id: 320, pl: "emancypacja", en: "emancipation" },
  { id: 321, pl: "emocja", en: "emotion" },
  { id: 322, pl: "empatia", en: "empathy" },
  { id: 323, pl: "empiryczny", en: "empirical" },
  { id: 324, pl: "energiczność", en: "energy" },
  { id: 325, pl: "enkapsulacja", en: "encapsulation" },
  { id: 326, pl: "entuzjazm", en: "enthusiasm" },
  { id: 327, pl: "epidemia", en: "epidemic" },
  { id: 328, pl: "epoka", en: "epoch" },
  { id: 329, pl: "epopeja", en: "epic" },
  { id: 330, pl: "erupcja", en: "eruption" },
  { id: 331, pl: "esencja", en: "essence" },
  { id: 332, pl: "eskapada", en: "escapade" },
  { id: 333, pl: "estrada", en: "stage" },
  { id: 334, pl: "etap", en: "stage" },
  { id: 335, pl: "eter", en: "ether" },
  { id: 336, pl: "etiologia", en: "etiology" },
  { id: 337, pl: "etnografia", en: "ethnography" },
  { id: 338, pl: "etykieta", en: "label" },
  { id: 339, pl: "euforia", en: "euphoria" },
  { id: 340, pl: "ewaluacja", en: "evaluation" },
  { id: 341, pl: "ewangelizacja", en: "evangelization" },
  { id: 342, pl: "ewidencja", en: "evidence" },
  { id: 343, pl: "ewolucja", en: "evolution" },
  { id: 344, pl: "fakt", en: "fact" },
  { id: 345, pl: "fascynacja", en: "fascination" },
  { id: 346, pl: "fatalizm", en: "fatalism" },
  { id: 347, pl: "faza", en: "phase" },
  { id: 348, pl: "fenomen", en: "phenomenon" },
  { id: 349, pl: "filantropia", en: "philanthropy" },
  { id: 350, pl: "filozofia", en: "philosophy" },
  { id: 351, pl: "filtracja", en: "filtration" },
  { id: 352, pl: "finanse", en: "finance" },
  { id: 353, pl: "firma", en: "company" },
  { id: 354, pl: "fizjologia", en: "physiology" },
  { id: 355, pl: "fizyk", en: "physicist" },
  { id: 356, pl: "fluktuacja", en: "fluctuation" },
  { id: 357, pl: "formalizm", en: "formalism" },
  { id: 358, pl: "formularz", en: "form" },
  { id: 359, pl: "forteca", en: "fortress" },
  { id: 360, pl: "frakcja", en: "fraction" },
  { id: 361, pl: "frustracja", en: "frustration" },
  { id: 362, pl: "funkcja", en: "function" },
  { id: 363, pl: "fundacja", en: "foundation" },
  { id: 364, pl: "fuzja", en: "fusion" },
  { id: 365, pl: "futuryzm", en: "futurism" },
  { id: 366, pl: "galaktyka", en: "galaxy" },
  { id: 367, pl: "galeria", en: "gallery" },
  { id: 368, pl: "gatunek", en: "species" },
  { id: 369, pl: "genetyka", en: "genetics" },
  { id: 370, pl: "geneza", en: "genesis" },
  { id: 371, pl: "geniusz", en: "genius" },
  { id: 372, pl: "geografia", en: "geography" },
  { id: 373, pl: "geologia", en: "geology" },
  { id: 374, pl: "germanistyka", en: "German studies" },
  { id: 375, pl: "gospodarka", en: "economy" },
  { id: 376, pl: "grawerowanie", en: "engraving" },
  { id: 377, pl: "graffiti", en: "graffiti" },
  { id: 378, pl: "grupa", en: "group" },
  { id: 379, pl: "gwałt", en: "rape" },
  { id: 380, pl: "gwiazda", en: "star" },
  { id: 381, pl: "haki", en: "hooks" },
  { id: 382, pl: "harcerstwo", en: "scouting" },
  { id: 383, pl: "harmonia", en: "harmony" },
  { id: 384, pl: "hekatomba", en: "hecatomb" },
  { id: 385, pl: "herbata", en: "tea" },
  { id: 386, pl: "heroizm", en: "heroism" },
  { id: 387, pl: "heterogeniczny", en: "heterogeneous" },
  { id: 388, pl: "hierarchia", en: "hierarchy" },
  { id: 389, pl: "histeria", en: "hysteria" },
  { id: 390, pl: "historia", en: "history" },
  { id: 391, pl: "hodowla", en: "breeding" },
  { id: 392, pl: "hotel", en: "hotel" },
  { id: 393, pl: "humanizm", en: "humanism" },
  { id: 394, pl: "humor", en: "humor" },
  { id: 395, pl: "huragan", en: "hurricane" },
  { id: 396, pl: "hybryda", en: "hybrid" },
  { id: 397, pl: "hydraulika", en: "hydraulics" },
  { id: 398, pl: "hymn", en: "anthem" },
  { id: 399, pl: "hipoteza", en: "hypothesis" },
  { id: 400, pl: "ideologia", en: "ideology" },
    { id: 401, pl: "identyfikacja", en: "identification" },
  { id: 402, pl: "ideogram", en: "ideogram" },
  { id: 403, pl: "idiosynkrazja", en: "idiosyncrasy" },
  { id: 404, pl: "ignorancja", en: "ignorance" },
  { id: 405, pl: "iluzja", en: "illusion" },
  { id: 406, pl: "imaginacja", en: "imagination" },
  { id: 407, pl: "imigracja", en: "immigration" },
  { id: 408, pl: "impet", en: "momentum" },
  { id: 409, pl: "implantacja", en: "implantation" },
  { id: 410, pl: "implementacja", en: "implementation" },
  { id: 411, pl: "impresja", en: "impression" },
  { id: 412, pl: "impulsywność", en: "impulsiveness" },
  { id: 413, pl: "inauguracja", en: "inauguration" },
  { id: 414, pl: "incydent", en: "incident" },
  { id: 415, pl: "indeks", en: "index" },
  { id: 416, pl: "indoktrynacja", en: "indoctrination" },
  { id: 417, pl: "indywidualizm", en: "individualism" },
  { id: 418, pl: "indywidualność", en: "individuality" },
  { id: 419, pl: "industria", en: "industry" },
  { id: 420, pl: "infekcja", en: "infection" },
  { id: 421, pl: "infrastruktura", en: "infrastructure" },
  { id: 422, pl: "informacja", en: "information" },
  { id: 423, pl: "inicjatywa", en: "initiative" },
  { id: 424, pl: "infrastruktura", en: "infrastructure" },
  { id: 425, pl: "inspekcja", en: "inspection" },
  { id: 426, pl: "instalacja", en: "installation" },
  { id: 427, pl: "instytucja", en: "institution" },
  { id: 428, pl: "integracja", en: "integration" },
  { id: 429, pl: "inteligencja", en: "intelligence" },
  { id: 430, pl: "intensywność", en: "intensity" },
  { id: 431, pl: "interakcja", en: "interaction" },
  { id: 432, pl: "interes", en: "interest" },
  { id: 433, pl: "internet", en: "internet" },
  { id: 434, pl: "interpretacja", en: "interpretation" },
  { id: 435, pl: "interwencja", en: "intervention" },
  { id: 436, pl: "intuicja", en: "intuition" },
  { id: 437, pl: "intryga", en: "intrigue" },
  { id: 438, pl: "inwazja", en: "invasion" },
  { id: 439, pl: "inwestycja", en: "investment" },
  { id: 440, pl: "izolacja", en: "isolation" },
  { id: 441, pl: "jakość", en: "quality" },
  { id: 442, pl: "jazda", en: "ride" },
  { id: 443, pl: "jednostka", en: "unit" },
  { id: 444, pl: "język", en: "language" },
  { id: 445, pl: "jazgot", en: "clamor" },
  { id: 446, pl: "jeden", en: "one" },
  { id: 447, pl: "jedyny", en: "only" },
  { id: 448, pl: "jedwab", en: "silk" },
  { id: 449, pl: "jedzenie", en: "food" },
  { id: 450, pl: "jednostronność", en: "one-sidedness" },
  { id: 451, pl: "jeździectwo", en: "horsemanship" },
  { id: 452, pl: "joga", en: "yoga" },
  { id: 453, pl: "jubilat", en: "jubilarian" },
  { id: 454, pl: "jubileusz", en: "jubilee" },
  { id: 455, pl: "judykatura", en: "judiciary" },
  { id: 456, pl: "jugendstil", en: "Art Nouveau" },
  { id: 457, pl: "jutro", en: "tomorrow" },
  { id: 458, pl: "jutrzenka", en: "dawn" },
  { id: 459, pl: "kabaret", en: "cabaret" },
  { id: 460, pl: "kabel", en: "cable" },
  { id: 461, pl: "kadencja", en: "term" },
  { id: 462, pl: "kadra", en: "staff" },
  { id: 463, pl: "kalendarz", en: "calendar" },
  { id: 464, pl: "kamera", en: "camera" },
  { id: 465, pl: "kampania", en: "campaign" },
  { id: 466, pl: "kanał", en: "channel" },
  { id: 467, pl: "kanon", en: "canon" },
  { id: 468, pl: "katalog", en: "catalog" },
  { id: 469, pl: "katastrofa", en: "catastrophe" },
  { id: 470, pl: "katedra", en: "cathedral" },
  { id: 471, pl: "katolicyzm", en: "Catholicism" },
  { id: 472, pl: "kaucja", en: "deposit" },
  { id: 473, pl: "kawiarnia", en: "cafe" },
  { id: 474, pl: "kawa", en: "coffee" },
  { id: 475, pl: "kazanie", en: "sermon" },
  { id: 476, pl: "kecepka", en: "cap" },
  { id: 477, pl: "klasa", en: "class" },
  { id: 478, pl: "klatka", en: "cage" },
  { id: 479, pl: "klimat", en: "climate" },
  { id: 480, pl: "klinika", en: "clinic" },
  { id: 481, pl: "klucz", en: "key" },
  { id: 482, pl: "knajpa", en: "pub" },
  { id: 483, pl: "kobiecość", en: "femininity" },
  { id: 484, pl: "koc", en: "blanket" },
  { id: 485, pl: "kod", en: "code" },
  { id: 486, pl: "kolej", en: "railway" },
  { id: 487, pl: "kolekcja", en: "collection" },
  { id: 488, pl: "kolejka", en: "queue" },
  { id: 489, pl: "kolęda", en: "carol" },
  { id: 490, pl: "komedia", en: "comedy" },
  { id: 491, pl: "komentarz", en: "comment" },
  { id: 492, pl: "komitet", en: "committee" },
  { id: 493, pl: "komunikacja", en: "communication" },
  { id: 494, pl: "komunia", en: "communion" },
  { id: 495, pl: "komunikat", en: "announcement" },
  { id: 496, pl: "kompozycja", en: "composition" },
  { id: 497, pl: "kompromis", en: "compromise" },
  { id: 498, pl: "komputer", en: "computer" },
  { id: 499, pl: "koncert", en: "concert" },
  { id: 500, pl: "konferencja", en: "conference" }
];




const SLOT_COUNT = 5;

// Komponent

export default function WordMatchGame() {
  const [difficulty, setDifficulty] = useState<Difficulty>("easy");
  const [words, setWords] = useState<Word[]>(easyWords);
  const [plSlots, setPlSlots] = useState<SlotWord[]>(
    Array(SLOT_COUNT).fill({ id: null, word: null })
  );
  const [enSlots, setEnSlots] = useState<SlotWord[]>(
    Array(SLOT_COUNT).fill({ id: null, word: null })
  );
  const [usedIds, setUsedIds] = useState<number[]>([]);
  const [selected, setSelected] = useState<{
    side: "pl" | "en";
    slotIndex: number;
    id: number;
  } | null>(null);
  const [error, setError] = useState<{
    side: "pl" | "en";
    slotIndex: number;
  } | null>(null);
  const [correctHighlight, setCorrectHighlight] = useState<
    { plIndex: number; enIndex: number } | null
  >(null);
  const [score, setScore] = useState(0);
  const [errors, setErrors] = useState(0);
  const [startTime, setStartTime] = useState(Date.now());
  const [now, setNow] = useState(Date.now());

  useEffect(() => {
    const interval = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(interval);
  }, []);

  const shuffleArray = <T,>(arr: T[]) => [...arr].sort(() => Math.random() - 0.5);

  const getEmptySlots = (slots: SlotWord[]) =>
    slots.map((slot, idx) => (slot.id === null ? idx : -1)).filter((i) => i !== -1);

  const addNewPairs = (n: number) => {
    let plCopy = [...plSlots];
    let enCopy = [...enSlots];
    let used = [...usedIds];

    const emptyPlSlots = shuffleArray(getEmptySlots(plCopy));
    const emptyEnSlots = shuffleArray(getEmptySlots(enCopy));
    const slotsToFill = Math.min(emptyPlSlots.length, emptyEnSlots.length, n);
    const candidates = shuffleArray(words.filter((w) => !used.includes(w.id))).slice(
      0,
      slotsToFill
    );

    for (let i = 0; i < slotsToFill; i++) {
      const word = candidates[i];
      plCopy[emptyPlSlots[i]] = { id: word.id, word: word.pl };
      enCopy[emptyEnSlots[i]] = { id: word.id, word: word.en };
      used.push(word.id);
    }

    setPlSlots(plCopy);
    setEnSlots(enCopy);
    setUsedIds(used);
  };

  useEffect(() => {
    resetGame();
  }, [difficulty]);

  const resetGame = () => {
    setUsedIds([]);
    setPlSlots(Array(SLOT_COUNT).fill({ id: null, word: null }));
    setEnSlots(Array(SLOT_COUNT).fill({ id: null, word: null }));
    setSelected(null);
    setCorrectHighlight(null);
    setError(null);
    setScore(0);
    setErrors(0);
    setStartTime(Date.now());

    setWords(
      difficulty === "easy"
        ? easyWords
        : difficulty === "medium"
        ? mediumWords
        : hardWords
    );

    setTimeout(() => addNewPairs(SLOT_COUNT), 100);
  };

  const handleClick = (side: "pl" | "en", slotIndex: number) => {
    const slots = side === "pl" ? plSlots : enSlots;
    const slot = slots[slotIndex];
    if (!slot.id || (error && error.side === side && error.slotIndex === slotIndex) || correctHighlight)
      return;

    if (!selected) {
      setSelected({ side, slotIndex, id: slot.id });
      return;
    }

    if (selected.side === side && selected.slotIndex === slotIndex) {
      setSelected(null);
      return;
    }

    if (selected.id === slot.id && selected.side !== side) {
      const plIndex = side === "pl" ? slotIndex : selected.slotIndex;
      const enIndex = side === "en" ? slotIndex : selected.slotIndex;

      setCorrectHighlight({ plIndex, enIndex });
      setSelected(null);
      setScore((s) => s + 1);

      setTimeout(() => {
        setPlSlots((prev) =>
          prev.map((s, i) => (i === plIndex ? { id: null, word: null } : s))
        );
        setEnSlots((prev) =>
          prev.map((s, i) => (i === enIndex ? { id: null, word: null } : s))
        );
        setCorrectHighlight(null);
        const totalWords =
          plSlots.filter((s) => s.id !== null).length +
          enSlots.filter((s) => s.id !== null).length;
        if (totalWords - 2 < 6) addNewPairs(2);
      }, 500);

      return;
    }

    // Zliczanie błędów:
    setErrors((e) => e + 1);
    setError({ side, slotIndex });
    setSelected(null);
    setTimeout(() => setError(null), 1000);
  };

const getButtonClass = (
  side: "pl" | "en",
  slotIndex: number,
  slot: SlotWord
) => {
  let base =
    "px-4 py-2 rounded-xl text-left shadow transition-colors duration-300 cursor-pointer select-none h-12 flex items-center ";

  if (slot.id === null) return base + "bg-transparent cursor-default";

  if (
    correctHighlight &&
    ((side === "pl" && correctHighlight.plIndex === slotIndex) ||
      (side === "en" && correctHighlight.enIndex === slotIndex))
  ) {
    return base + "bg-green-500 text-white";
  }

  if (error && error.side === side && error.slotIndex === slotIndex) {
    return base + "bg-rose-500 text-white";
  }

  if (selected && selected.side === side && selected.slotIndex === slotIndex) {
    return base + "bg-yellow-500 text-white";
  }

  return base + "bg-indigo-600 border border-indigo-500 text-white hover:bg-indigo-500";
};


  const gameTime = Math.floor((now - startTime) / 1000);

  return (
    <div className="min-h-screen bg-gray-900 p-6 flex flex-col items-center text-white">
      <h1 className="text-2xl font-bold mb-6">Gra w dopasowywanie słów</h1>

      {/* Poziomy */}
      <div className="mb-6 flex gap-4">
        {(["easy", "medium", "hard"] as Difficulty[]).map((level) => (
          <button
            key={level}
            onClick={() => setDifficulty(level)}
            className={`flex items-center gap-2 px-4 py-2 rounded-full border border-gray-600 transition-colors duration-200
              ${
                difficulty === level
                  ? "bg-blue-400 text-white"
                  : "bg-gray-800 text-blue-400 hover:bg-gray-700"
              }`}
          >
            <span>
              {level === "easy"
                ? "⭐"
                : level === "medium"
                ? "⭐⭐"
                : "⭐⭐⭐"}
            </span>
            {level === "easy"
              ? "Łatwy"
              : level === "medium"
              ? "Średni"
              : "Trudny"}
          </button>
        ))}
      </div>

      {/* Plansza */}
      <div className="flex justify-between w-full max-w-3xl gap-6">
        <div className="w-1/2 flex flex-col gap-4">
          {plSlots.map((slot, idx) => (
            <button
              key={"pl" + idx}
              onClick={() => handleClick("pl", idx)}
              className={getButtonClass("pl", idx, slot)}
              disabled={slot.id === null || Boolean(correctHighlight)}
            >
              {slot.word ?? "\u00A0"}
            </button>
          ))}
        </div>
        <div className="w-1/2 flex flex-col gap-4">
          {enSlots.map((slot, idx) => (
            <button
              key={"en" + idx}
              onClick={() => handleClick("en", idx)}
              className={getButtonClass("en", idx, slot)}
              disabled={slot.id === null || Boolean(correctHighlight)}
            >
              {slot.word ?? "\u00A0"}
            </button>
          ))}
        </div>
      </div>

      {/* Statystyki */}
      <div className="mt-8 text-lg space-y-1">
        <p>
          Punkty: <strong>{score}</strong>
        </p>
        <p>
          Błędy: <strong>{errors}</strong>
        </p>
        <p>
          Czas gry: <strong>{gameTime}s</strong>
        </p>
      </div>

      {/* Reset */}
      <button
        onClick={resetGame}
        className="mt-6 px-6 py-2 rounded-full bg-green-400 text-gray-900 font-semibold hover:bg-green-500 transition"
      >
        Zagraj ponownie
      </button>
    </div>
  );
}